forge_support: true
player_limit: -1
permissions:
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
timeout: 30000
log_commands: false
online_mode: true
disabled_commands:
  - disabledcommandhere
servers:
  lobby:
    motd: ' '
    address: localhost:25565
    restricted: false
listeners:
  - query_port: 25577
    motd: '&1Another Bungee server'
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    ping_passthrough: false
    priorities:
      - lobby
    bind_local_address: true
    host: 0.0.0.0:25577
    max_players: 1
    tab_size: 60
    force_default_server: false
ip_forward: true
network_compression_threshold: 256
prevent_proxy_connections: false
groups:
  md_5:
    - admin
connection_throttle: 4000
stats: c58c914b-6154-4417-8dba-2015835dd187
connection_throttle_limit: 3
log_pings: true
